# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "David J. Rappaport"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Personal homepage for David J. Rappaport, showcasing examples of my engineering, design, and other creative work."

# The subpath of your site, e.g. /blog, for generating urls
baseurl: 

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://rappaport.me"

# Author information - author info at the bottom of the post
author_name: "David J. Rappaport"

# Social links in the site footer
linkedin_username: "djrapp"
instagram_username: "d_rappaport"

